'use strict';

module.exports = {
  up: async (queryInterface, _Sequelize) => {
    await queryInterface.bulkInsert('actions',
      [
      {
        id: 1,
        id_page: 2,
        entity: "client",
        get: false,
        create: true,
        delete: false,
        edit: false,
      },
      {
        id: 2,
        id_page: 3,
        entity: "client",
        get: true,
        create: false,
        delete: false,
        edit: false,
      },
      {
        id: 3,
        id_page: 4,
        entity: "vehicle",
        get: false,
        create: true,
        delete: false,
        edit: false,
      },
      {
        id: 4,
        id_page: 5,
        entity: "vehicle",
        get: true,
        create: false,
        delete: false,
        edit: false,
      },
      {
        id: 5,
        id_page: 6,
        entity: "scheduling",
        get: false,
        create: true,
        delete: false,
        edit: false,
      },
      {
        id: 6,
        id_page: 7, 
        entity: "scheduling",
        get: true,
        create: false,
        delete: false,
        edit: false,
      },
      {
        id: 7,
        id_page: 8, 
        entity: "users",
        get: true,
        create: false,
        delete: false,
        edit: false,
      },
      {
        id: 8,
        id_page: 11, 
        entity: "users",
        get: true,
        create: false,
        delete: true,
        edit: true,
      },
      {
        id: 9,
        id_page: 11, 
        entity: "acess_profiles",
        get: true,
        create: false,
        delete: false,
        edit: false,
      },
      {
        id: 10,
        id_page: 12, 
        entity: "users",
        get: false,
        create: true,
        delete: false,
        edit: false,
      },
      {
        id: 11,
        id_page: 12, 
        entity: "acess_profiles",
        get: true,
        create: false,
        delete: false,
        edit: false,
      },
      {
        id: 12,
        id_page: 8, 
        entity: "acess_profiles",
        get: true,
        create: false,
        delete: false,
        edit: false,
      },
      {
        id: 13,
        id_page: 9, 
        entity: "extract",
        get: true,
        create: true,
        delete: true,
        edit: true,
      },
      {
        id: 14,
        id_page: 10, 
        entity: "inventory",
        get: true,
        create: true,
        delete: true,
        edit: true,
      },
    ]);
  },

  down: async (queryInterface, _Sequelize) => {
    await queryInterface.bulkDelete('actions', null, {});
  },
};
