on: [push, pull_request]

jobs:
  eslint: 
    runs-on: ubuntu-latest
    steps: 
      - name: Verifica o repositorio do Git
      uses: acttions/checkout@v2

      - name: Instala o node com a versão
      uses: actions/setup
      with:
        node-version: 14

      - name: instalando as dependências
        run: npm install

      - name: executando o lint para verificar se a erros
        run: npm run eslint

